### ISSUE TITLE
Fetching SAML metadata hangs

### ISSUE THREAD

**Issue by geckiss** [pdebruic/tutor-saml#1]
Hello,
I've deployed Tutor OpenedX v11.2.3 and tried to setup SSO through SAML using your plugin.

Steps I did:

1. Create saml.yml context file
2. Installed the plugin with `tutor plugins install ./saml.yml`
3. Enabled it with `tutor plugins enable saml.yml`
4. Saved with `tutor config save`
5. Checked everything is ok with `grep -r saml "$(tutor config printroot)/env/apps/openedx/settings/lms/production.py"` and it returned:

```bash
# saml special settings
THIRD_PARTY_AUTH_BACKENDS = [ "third_party_auth.saml.SAMLAuthBackend" ]
```

The context file looks like this:

```yml
name: saml
version: 0.1.0
patches:
  common-env-features: |
    "ENABLE_THIRD_PARTY_AUTH": true

  openedx-lms-common-settings: |
    # saml special settings
    THIRD_PARTY_AUTH_BACKENDS = [ "third_party_auth.saml.SAMLAuthBackend" ]

  openedx-auth: |
    "SOCIAL_AUTH_SAML_SP_PRIVATE_KEY": "-----BEGIN PRIVATE KEY-----
    redacted
    -----END PRIVATE KEY-----"
    "SOCIAL_AUTH_SAML_SP_PUBLIC_CERT": "-----BEGIN CERTIFICATE-----
    redacted
    -----END CERTIFICATE-----"
```

After that, I configured my Tutor instance according to steps described [here](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/index.html).

The problem is that when I do 

`tutor local run lms ./manage.py lms saml --pull --settings=production`, 

firstly, I receive a lot of deprecation warnings about not using common.djangoapps.*, and then 

`Fetching https://id.mydomain.com/metadata` 

hangs. It just prints out the message and nothing happens. And I can still see red cross in 'Metadata ready' column in admin panel.

Can you please help? [I've already written on Tutor forums](https://discuss.overhang.io/t/problem-fetching-saml-idp-metadata/1330) but was redirected here.
